import { useEffect, useCallback, useState, useMemo } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useSession } from '@/hooks/useSession';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';
import { 
  ArrowLeft, 
  Save, 
  Menu,
  Plus,
  BarChart3,
  FileDown,
} from 'lucide-react';
import dnaiLogo from '@/assets/dnai-logo.png';
import { QuestionPanel } from '@/components/canvas/QuestionPanel';
import { CanvasNode } from '@/components/canvas/CanvasNode';
import { ConnectorsSVG } from '@/components/canvas/CanvasConnector';
import { SessionNode } from '@/types/session';
import { 
  calculateFunnelPositions, 
  NODE_LEVELS, 
  FUNNEL_LEVELS,
  getCanvasCenterX,
} from '@/utils/funnelLayout';

export default function Canvas() {
  const { sessionId } = useParams<{ sessionId: string }>();
  const navigate = useNavigate();
  const { currentSession, loadSession, addNode, updateNode } = useSession();
  const { user } = useAuth();
  const [canvasWidth, setCanvasWidth] = useState(1000);

  useEffect(() => {
    if (sessionId && !currentSession) {
      loadSession(sessionId);
    }
  }, [sessionId, currentSession, loadSession]);

  // Redirect if no session found
  if (!sessionId) {
    navigate('/');
    return null;
  }

  // Calculate positioned nodes
  const positionedNodes = useMemo(() => {
    if (!currentSession?.nodes) return [];
    const centerX = getCanvasCenterX(canvasWidth);
    return calculateFunnelPositions(currentSession.nodes, centerX);
  }, [currentSession?.nodes, canvasWidth]);

  // Selected node for highlighting connections
  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null);

  // Handle node creation from question answers
  const handleNodeCreate = useCallback((nodeType: string, data: Record<string, any>) => {
    if (!currentSession) return;
    
    // Handle node updates (for volume/spend data)
    if (nodeType === 'lead-source-update') {
      const existingNode = currentSession.nodes.find(n => 
        n.sourceId === data.sourceId
      );
      if (existingNode && updateNode) {
        updateNode(existingNode.id, {
          volume: data.volume ?? existingNode.volume,
          label: data.label || existingNode.label,
          spend: data.spend ?? existingNode.spend,
        });
      }
      return;
    }

    // Handle leak alerts
    if (nodeType === 'leak-alert') {
      addNode({
        type: 'custom' as any,
        label: data.label || 'Leak Point',
        volume: 0,
        conversionRate: 0,
        value: 0,
        position: { x: 0, y: 0 },
        connections: [],
        isLeak: true,
        leakReason: data.leakReason,
      });
      return;
    }

    // Handle intake-to-source connection mapping
    if (nodeType === 'intake-connection') {
      const intakeNode = currentSession.nodes.find(n => n.sourceId === data.intakeId);
      if (intakeNode && updateNode) {
        updateNode(intakeNode.id, {
          sourceConnections: [...(intakeNode.sourceConnections || []), data.leadSourceId],
        });
      }
      return;
    }
    
    // Create new node (id is generated by addNode)
    addNode({
      type: nodeType as any,
      label: data.label || getNodeLabel(nodeType, data),
      volume: data.volume || 0,
      conversionRate: data.conversionRate || 0,
      value: data.value || 0,
      position: { x: 0, y: 0 },
      connections: [],
      sourceId: data.sourceId,
      spend: data.spend,
      isLeak: data.isLeak,
      leakReason: data.leakReason,
    });
  }, [currentSession, addNode, updateNode]);

  return (
    <div className="flex h-screen flex-col bg-background">
      {/* Top Header */}
      <header className="flex h-14 items-center justify-between border-b border-border bg-card px-4 shrink-0">
        <div className="flex items-center gap-4">
          {/* Logo & Back */}
          <Button 
            variant="ghost" 
            size="sm" 
            onClick={() => navigate('/')}
            className="gap-2"
          >
            <ArrowLeft className="h-4 w-4" />
            <img src={dnaiLogo} alt="DNAi" className="h-6 w-auto" />
          </Button>
          
          {/* Session Info */}
          <div className="hidden md:flex items-center gap-2 text-sm">
            <span className="font-semibold text-foreground">
              {currentSession?.clientName || 'New Session'}
            </span>
            {currentSession?.industry && (
              <>
                <span className="text-muted-foreground">|</span>
                <span className="text-muted-foreground capitalize">
                  {currentSession.industry.replace('-', ' ')}
                </span>
              </>
            )}
          </div>
        </div>

        {/* Header Actions */}
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" className="gap-2">
            <Save className="h-4 w-4" />
            <span className="hidden sm:inline">Save</span>
          </Button>
          <Button variant="ghost" size="icon" className="h-8 w-8">
            <Menu className="h-4 w-4" />
          </Button>
        </div>
      </header>

      {/* Main Canvas Area - 3 Column Layout */}
      <div className="flex flex-1 overflow-hidden">
        {/* Left Sidebar - Questions Panel */}
        <aside className="w-80 border-r border-border bg-card flex flex-col shrink-0 hidden lg:flex">
          <QuestionPanel 
            sessionId={sessionId} 
            onNodeCreate={handleNodeCreate}
          />
        </aside>

        {/* Center Canvas */}
        <main 
          className="flex-1 relative overflow-auto bg-background"
          ref={(el) => {
            if (el) {
              const width = el.clientWidth;
              if (width !== canvasWidth) {
                setCanvasWidth(width);
              }
            }
          }}
        >
          {/* Canvas Grid Background */}
          <div 
            className="absolute inset-0 min-h-[900px]"
            style={{
              backgroundImage: `
                linear-gradient(to right, hsl(var(--border) / 0.3) 1px, transparent 1px),
                linear-gradient(to bottom, hsl(var(--border) / 0.3) 1px, transparent 1px)
              `,
              backgroundSize: '24px 24px',
            }}
          />

          {/* Funnel Level Labels */}
          <div className="absolute left-4 top-0 bottom-0 w-24 pointer-events-none">
            {FUNNEL_LEVELS.map((level) => (
              <div
                key={level.name}
                className="absolute text-xs text-muted-foreground/50 font-medium uppercase tracking-wider"
                style={{ top: level.yOffset + 20 }}
              >
                {level.name.replace(/-/g, ' ')}
              </div>
            ))}
          </div>

          {/* Canvas Content - Empty State */}
          {(!currentSession?.nodes || currentSession.nodes.length === 0) && (
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="text-center max-w-md p-8">
                <div className="mb-6 inline-flex h-20 w-20 items-center justify-center rounded-2xl bg-accent/10 border border-accent/20">
                  <Plus className="h-10 w-10 text-accent" />
                </div>
                <h2 className="mb-2 text-xl font-semibold text-foreground">
                  Start Building Your Map
                </h2>
                <p className="mb-6 text-muted-foreground text-sm">
                  Answer the questions on the left to guide your discovery call. Nodes will be created automatically as you progress.
                </p>
              </div>
            </div>
          )}

          {/* SVG for Connectors */}
          {positionedNodes.length > 0 && (
            <ConnectorsSVG 
              nodes={positionedNodes} 
              selectedNodeId={selectedNodeId || undefined}
            />
          )}

          {/* Render Nodes */}
          {positionedNodes.length > 0 && (
            <div className="absolute inset-0 min-h-[900px]">
              {positionedNodes.map((node) => (
                <CanvasNode
                  key={node.id}
                  node={node}
                  isSelected={node.id === selectedNodeId}
                  onClick={(n) => setSelectedNodeId(n.id === selectedNodeId ? null : n.id)}
                />
              ))}
            </div>
          )}

          {/* Canvas Action Bar */}
          <div className="absolute bottom-6 left-1/2 -translate-x-1/2 flex items-center gap-2 p-2 rounded-xl bg-card border border-border shadow-lg">
            <Button variant="ghost" size="sm" className="gap-2">
              <BarChart3 className="h-4 w-4" />
              Funnel View
            </Button>
            <div className="w-px h-6 bg-border" />
            <Button variant="ghost" size="sm" className="gap-2">
              <FileDown className="h-4 w-4" />
              Export PDF
            </Button>
          </div>
        </main>

        {/* Right Sidebar - Metrics Panel */}
        <aside className="w-80 border-l border-border bg-card flex flex-col shrink-0 hidden xl:flex">
          <div className="p-4 border-b border-border border-t-2 border-t-accent">
            <h2 className="font-semibold text-sm flex items-center gap-2">
              <span className="text-lg">📊</span>
              Metrics
            </h2>
          </div>

          {/* Metrics Content - Placeholder */}
          <div className="flex-1 overflow-auto p-4 scrollbar-thin">
            <div className="space-y-6">
              {/* Funnel Breakdown */}
              <div>
                <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">
                  Funnel Breakdown
                </h3>
                {positionedNodes.length > 0 ? (
                  <div className="space-y-2">
                    {positionedNodes.map(node => (
                      <div key={node.id} className="flex items-center justify-between text-sm">
                        <span className="text-muted-foreground truncate flex-1">{node.label}</span>
                        {node.volume > 0 && (
                          <span className="font-medium">{node.volume}</span>
                        )}
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-8 text-muted-foreground">
                    <BarChart3 className="h-10 w-10 mx-auto mb-3 opacity-40" />
                    <p className="text-sm">No data yet</p>
                    <p className="text-xs">Answer questions to see metrics</p>
                  </div>
                )}
              </div>

              {/* Top Leak Alert - Hidden until data */}
              <div className="p-4 rounded-lg border-2 border-dashed border-destructive/30 bg-destructive/5">
                <h3 className="text-xs font-semibold text-destructive uppercase tracking-wider mb-2">
                  Top Leak
                </h3>
                <p className="text-sm text-muted-foreground">
                  Leaks will appear here once you add conversion data
                </p>
              </div>

              {/* Revenue at Risk */}
              <div className="p-4 rounded-lg bg-muted/50">
                <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
                  Revenue at Risk
                </h3>
                <p className="text-2xl font-bold text-foreground">$0</p>
                <p className="text-xs text-muted-foreground mt-1">
                  Total monthly leakage
                </p>
              </div>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}

// Helper: Get node label from type and data
function getNodeLabel(nodeType: string, data: Record<string, any>): string {
  // If a label was provided, use it
  if (data.label) return data.label;
  
  // Default labels
  const labels: Record<string, string> = {
    'lead-source': 'Lead Source',
    'intake': 'Intake',
    'decision': 'Qualification',
    'conversion': 'Conversion',
    'close': 'Close',
    'fulfillment': 'Fulfillment',
    'review': 'Reviews & Referrals',
  };
  return labels[nodeType] || 'Custom';
}
